name: flutter_widget_catalog
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.18.2 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.5
  widget_with_codeview: ^2.0.1+2
  page_transition: ^2.0.9
  url_launcher: ^6.1.6
  shared_preferences: ^2.0.15
  dart_code_viewer2: ^1.0.0
  font_awesome_flutter: ^10.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.1
  flutter_launcher_icons: ^0.10.0

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icons/app_icon.png"
  image_path_ios: "assets/icons/app_icon_ios.jpg"
  min_sdk_android: 19
  web:
    generate: true
    image_path: "assets/icons/app_icon.png"
    background_color: "#hexcode"
    theme_color: "#hexcode"
  windows:
    generate: true
    image_path: "assets/icons/app_icon.png"
    icon_size: 48 # min:48, max:256, default: 48

flutter:

  uses-material-design: true

  assets:
    - assets/images/
    - assets/icons/
    - lib/views/basics/
    - lib/views/buttons/
    - lib/views/single_child_layouts/
    - lib/views/multi_child_layouts/
    - lib/views/inputs/
    - lib/views/touch_interactions/
    - lib/views/routing/
    - lib/views/scrolling/
    - lib/views/painting/
    - lib/views/animation/
    - lib/views/transition/

  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf


